### PR TITLE
Adds a final step for circleci builds

### PR DESCRIPTION
**Pull request by PowerSchill**
Enables green-build requirements for pull requests.

### CODE REVIEW

**Comment by PowerSchill** [comment]
The `gpsd.socket` service isn't starting because it can't assign the requested address. Is it safe to assume this is because there is no gps device attached to the vm?

**Comment by Sliim** [comment]
No, the `gpsd` service should start without any connected device

**Comment by Sliim** [comment]
I think your issue is on `kitchen-dokken` side..

Here is an example with `kitchen-docker` on travis with `debian-9` platform:
- Changes: https://github.com/sliim-cookbooks/kismet/commit/8a06ae7c
- Build: https://travis-ci.org/sliim-cookbooks/kismet/builds/635023937

**Comment by tas50** [comment]
Closing this since we're using Github Actions now

**Comment by Sliim** [comment]
Yes but the build fails on github action and it's the same issue...

**Pull request closed without merging**
